controle_updates = (
     "16/04/24: Add: Drive, Creed, Perks, Edges, Character Generator",

)

#Gemini.ai:
ambitions = [
    "Expose a major supernatural conspiracy.",
    "Eradicate a specific monstrous threat plaguing your city.",
    "Learn a powerful ritual to banish a powerful entity.",
    "Master a forgotten weapon specifically designed for hunting the supernatural.",
    "Forge an alliance with a powerful  supernatural creature.",
    "Uncover the truth behind a legendary monster hunter and their methods.",
    "Purify a corrupted holy site and reclaim its power.",
    "Close a major dimensional tear spewing forth horrors.",
    "Develop a foolproof method to identify and track any supernatural creature.",
    "Disrupt a major summoning ritual of a monstrous entity.",
    "Overcome a crippling fear related to the supernatural.",
    "Master your Hunter's Discipline (e.g., Dominate, Potence).",
    "Find a way to permanently suppress your Beast.",
    "Learn a lost language used by ancient monster hunters.",
    "Forge a lasting bond with your fellow Hunters.",
    "Heal the emotional scars inflicted by your encounters with the supernatural.",
    "Find a way to balance your Hunter life with normalcy.",
    "Uncover your forgotten past and any hidden talents.",
    "Become a mentor and leader for a new generation of Hunters.",
    "Find a way to truly understand the purpose of the Reckoning.",
    "Bring a corrupt supernatural powerbroker to justice.",
    "Expose a human organization collaborating with the darkness.",
    "Rescue innocent victims from a supernatural predator's grasp.",
    "Develop a code of ethics to guide your actions as a Hunter.",
    "Prevent a supernatural conflict from spilling over and harming innocents.",
    "Find a way to redeem a monstrous creature turned towards evil.",
    "Expose and dismantle a human cult worshipping darkness.",
    "Bring justice to a supernatural creature who committed a heinous crime.",
    "Establish a safe haven for humans caught in the crossfire of the Reckoning.",
    "Uncover a way to permanently destroy cursed objects that fuel evil.",
    "Uncover the secrets of a lost civilization with knowledge of combating the darkness.",
    "Decipher a cryptic ancient text detailing a powerful supernatural weapon.",
    "Learn the true history and origins of the different supernatural splats (e.g., vampires, werewolves).",
    "Find a way to safely communicate and gain knowledge from captured supernatural creatures.",
    "Explore a legendary haunted location rumored to hold secrets of the Reckoning.",
    "Uncover the true purpose and origin of the mysterious Hunter organization.",
    "Develop a comprehensive understanding of the supernatural world and its various factions.",
    "Learn a forgotten magic to combat specific supernatural threats.",
    "Become an expert tracker and investigator of supernatural phenomena.",
    "Find a way to permanently sever a powerful blood bond.",
    "Found a new Hunter organization dedicated to specific threats.",
    "Develop a new training regimen for future Hunters.",
    "Spread awareness of the supernatural threat to the human population.",
    "Gain the trust and support of a powerful human organization.",
    "Influence the political landscape to combat the supernatural threat indirectly.",
    "Create a powerful relic that aids future Hunters in their struggles.",
    "Develop a new technology specifically designed to combat various supernatural creatures.",
    "Become a legendary symbol of hope and resistance against the darkness.",
    "Leave behind a legacy of knowledge and wisdom for future Hunters.",
    "Unify various Hunter factions under a single banner.",
    "Learn to control the Beast's hunger and prevent Frenzy.",
    "Use the Beast's power for good while maintaining control.",
    "Find a way to permanently weaken or sever the connection to the Beast.",
    "Develop a deep understanding of the Beast's nature and origin.",
    "Embrace the Beast and become a monstrous force against darkness (caution advised).",
    "Find a way to permanently destroy a specific type of supernatural creature.",
    "Master a forgotten Hunter technique said to grant superhuman abilities.",
    "Recover a stolen artifact of immense power from a specific supernatural faction.",
    "Earn the respect and trust of a particular legendary Hunter.",
    "Uncover the truth behind a specific historical event with supernatural ties.",
    "Develop a unique fighting style specifically for hunting a specific creature type.",
    "Infiltrate and dismantle a specific supernatural organization from within.",
    "Find a way to permanently sever the connection between a specific human and a particular supernatural creature.",
    "Break a powerful supernatural curse plaguing your family lineage.",
    "Secure a permanent haven for a specific endangered supernatural creature (good-aligned).",
    "Master a specific forgotten Hunter ritual with a powerful effect.",
    "Learn the truth behind a specific haunting or cryptid legend in your local area.",
     "Find a way to utilize a powerful cursed object for good without succumbing to its darkness.",
    "Decide the fate of a captured monstrous creature: redemption, destruction, or unwilling ally?",
    "Expose a fellow Hunter's dark secret and corruption.",
    "Weigh the benefits of revealing the supernatural world to the public vs. the potential chaos.",
    "Make a pact with a lesser evil to defeat a greater one (beware the consequences).",
    "Find a way to achieve a peaceful coexistence between humans and the supernatural.",
    "Unravel the mysteries of the afterlife and the spirit world.",
    "Understand your place in the grand scheme of the Reckoning.",
    "Discover the true nature of your soul and its connection to the supernatural.",
    "Find a way to transcend the limitations of human mortality.",
    "Uncover the truth behind a cryptic message left by a deceased Hunter.",
    "Investigate a series of seemingly unrelated supernatural events and uncover the hidden connection.",
    "Infiltrate a seemingly mundane organization suspected of having a hidden supernatural agenda.",
    "Follow a trail of clues left behind by an ancient Hunter lineage.",
    "Decipher a series of cryptic symbols left behind by an unknown supernatural entity.",
    "Avenge the death of a loved one at the hands of a supernatural creature.",
    "Atone for a past mistake that led to the suffering of others.",
    "Find a way to break a powerful curse inflicted upon you or a loved one.",
    "Earn forgiveness from someone you wronged due to your actions as a Hunter.",
    "Master a dangerous form of forbidden magic to combat powerful supernatural threats.",
    "Uncover the secrets of a lost civilization rumored to have harnessed immense power.",
    "Seek out a powerful artifact rumored to grant the wielder dominion over specific supernatural creatures.",
    "Delve into the deepest secrets of your Hunter Discipline, risking corruption for greater power.",
    "Find yourself thrust into a leadership role within your Hunter organization.",
    "Uncover a hidden talent for diplomacy and forge alliances between Hunters and supernatural factions.",
    "Become a reluctant public figure due to your successful exploits against the darkness.",
    "Develop a unique psychic ability that aids you in hunting specific supernatural threats.",
    "Become a master detective, specializing in uncovering the supernatural elements behind seemingly mundane crimes.",
    "Develop a system for predicting and tracking supernatural activity within a specific region.",
    "Learn to identify subtle signs of supernatural influence in everyday objects and locations.",
    "Master the art of disguise and infiltration to move undetected amongst supernatural societies.",
    "Forge an unshakeable bond with your fellow Hunters, becoming a true team.",
    "Establish a safe haven and training ground for a new generation of Hunters.",
    "Develop a unique communication system to efficiently coordinate Hunter activities across a vast region.",
    "Unite various Hunter factions with differing ideologies under a common goal.",
    "Leave behind a legacy of teamwork and collaboration for future generations of Hunters."
     ]