perks_and_edges_text = {
    #Arsenal
    'arsenal':'Either borrowed from an old contact or put together in a garage, the Hunter has access to a wide variety of weapons that are generally not available to the public. This includes not only firearms but also melee weapons; however, this does not include explosives such as bombs, mines, or other munitions. These weapons are still mundane and are only available for a short period of time, either having to be returned to the contact, undergo severe maintenance, or break down due to their nature of being jerry-rigged.\n\n- Edge Pool: Intelligence + Craft for the Hunter who keeps and maintains their own arsenal. Manipulation + Streetwise for the Hunter who relies on contacts.\n\n- System: The Hunter is able to provide a single personal firearm or melee weapon upon winning a test at Difficulty 4. This test is made at the start of a scene, and the Hunter must have plausible access to their supplies or contacts. It can only be attempted once per scene, and the weapon can only be used for that scene, but later tests can provide the same or a similar weapon.\n\n- Perks: Team Requisition, Exotics, Special Features, untraceable',
    'team requisition':'Up to the margin of the win, the hunter can provide additional copies of the same weapon.',
    'exotics':'Arsenal: The Hunter is able to procure rare or one-of-a-kind weapons or ammunition. The Difficulty of the test can increase in the case of something extremely rare or unique, as determined by the Storyteller.\n\nOrdnance: Custom or otherwise rare substances can be obtained. The Storyteller should alter the Difficulty of the test in cases of exceedingly rare items. These items are not inherently supernatural but can exploit supernatural vulnerabilities.',
    'special features':'The weapon obtained comes with a number of special features, up to the margin of the win. The features can range from thermal signs to disguised cases, the Storyteller makes the final decision of what qualifies as a special feature',
    'untraceable':'Arsenal: The weapons are completely untraceable and will never lead authorities or quarry to the Hunters.\n\nFleet: The vehicles are completely untraceable and will never lead authorities or quarry to the Hunters.',

    #Fleet
    'fleet':'Either borrowed from a reliable contact or put together in a garage, the Hunter has access to a wide variety of personal or commercial vehicles on short notice. This does not include military vehicles such as tanks or attack aircraft.\n\n- Edge Pool: Intelligence + Technology for the Hunter who keeps and maintains their own fleet. Manipulation + Persuasion for the Hunter who relies on contacts.\n\n- System: The Hunter is able to provide a single vehicle for either public or commercial use, including boats and aircraft, upon winning a test at Difficulty 4. Outlandish requests should be vetted by the Storyteller with increasing Difficulty as needed. This test is made at the start of a scene, and the Hunter must have plausible access to their garage or contact. It can only be attempted once per scene, and the vehicle can only be used for that scene, but later tests can provide the same or a similar vehicle. This Edge does not grant the ability to pilot the vehicles provided.\n\n- Perks: Armor,Surveillance, Performance, Untraceable',
    'armor':'Vehicles are armored to withstand small firearms. Flying vehicles benefit less from the armor but do provide additional protection to passengers, adding two dice to their defense pools against ranged weaponry.',
    'surveillance':'Vehicles come with a wide variety of concealed surveillance tools. This equipment gives bonus dice equal to the margin on the Edge test on stakeouts from the vehicle, such as Awareness or Technology tests. However, this bonus cannot exceed three dice.',
    'performance':'Vehicles have superior driving and handling. This gives a bonus equal to the margin on the Edge test to win against pursuit-related Driving tests, however, this bonus cannot be more than 3 dice.',

    #Ordnance
    'ordnance':'Either obtained through one or many connections or put together by the Hunter themselves, the Hunter has access to various types of timed or remotely detonated munitions. Examples of these are anti-vehicle mines, C4 explosives, or demolition charges.\n\n- Edge Pool: Composure + Science for the Hunter who builds their own ordnance. Composure + Streetwise for the Hunter who relies on contacts.\n\n- System: The Hunter is able to provide a single mine or explosive upon winning a test at Difficulty 4. This test is made at the start of a scene and the Hunter must have plausible access to their supplies or contacts. It can only be attempted once per scene, and the explosive can only be used for that scene.\n\n- Perks: Multiple Payloads, Exotics, Non lethal Munitions, Disguised Delivery',
    'multiple payloads':'Up to the margin of the win, the hunter can provide additional copies of the same explosive.',
    'non lethal munitions':'The Hunter is able to obtain non-lethal munitions such as flash grenades or tear gas. The Storyteller should determine the effects of these substances on others, a good rule of thumb is a dice penalty equal to the margin of the Edge test. This penalty cannot exceed three dice.',
    'disguised delivery':'Items obtained are disguised as mundane items. The Difficulty to detect them is increased by the margin on the Edge test, but this penalty cannot exceed more than three dice.',

    #Library
    'library':'The Hunter has access to a wealth of information on a wide variety of topics and creatures through either a library filled with centuries-old texts or an encrypted database with all the latest research on the supernatural.\n\n- Edge Pool: Resolve + Academics\n\n- System: The Hunter must spend about a day researching their quarry before making an Edge test. The Storyteller decides what type of clue they receive upon a win and how vague it is, with the clarity and amount of information increasing based on the margin of the win. This can only be attempted once per scene, and once the Hunter succeeds, it cannot be used again until the next session.\n\nPerks: Where They Hide, How to Halt Them, Who They Are, How to Harm Them',
    'where they hide':"In addition to the clues obtained, any attempts to locate where the creature's lair is receive a bonus. This bonus is equal to the margin of the Edge test; it expires after use and cannot be greater than three dice.",
    "how to halt them":"In addition to the clues obtained, any attempts to ward or otherwise protect an area or person from the prey receive a bonus. This bonus is equal to the margin of the Edge test; it expires after use and cannot be greater than three dice. This does not apply to any direct attacks.",
    "who they are": "In addition to the clues obtained, any attempts to identify the prey receive a bonus. This bonus is equal to the margin of the Edge test; it expires after use and cannot be greater than three dice.",
    "how to harm them": "In addition to the clues obtained, any attempts to harm the prey by exploiting their supernatural weaknesses receive a bonus. This bonus is equal to the margin of the Edge test; it expires after use and cannot be greater than three dice.",

    #Improvised Gear
    "improvised gear":"With the objects and materials nearby, the Hunter is able to create any number of short-lived but useful tools to aid the cell\n\n- Edge Pool: Intelligence + Craft/Technology/Science depending on the tool or substance being made.\n\n- System: The Hunter is able to provide short-lived but useful equipment from ordinary items upon winning a test at Difficulty 4. This item can add to the use of a single Skill by adding a two-dice advantage at the Storyteller's discretion. It can also make certain actions that would have been impossible possible for the Hunters. The amount of time needed to create this item is determined by the Storyteller and may range from a few minutes to several hours. Creating these under duress, such as a firefight, is not possible. These items only last through one scene, and unless they have the associated perks, Hunters can only make one per scene.\n\nPerks: Frugal, Specialization, Mass Production, Speed Crafting",
    "frugal":"With their trinkets and tools on their person in a bag or another container, the Hunter can apply this Edge anywhere.",
    "specialization":"Specializing in a specific Skill, the Hunter now can produce items that have a 3-dice bonus instead of 2. This perk can be taken multiple times, but only once per Skill.",
    "mass production":"The Hunter can produce additional items equal to the margin of the test. These items are, however, all identical and grant the bonus to the same Skill. All other restrictions and Perks apply.",
    "speed crafting":"This Edge can now be used under duress, such as in firefights, and the Hunter crafts the tool in three turns minus the margin of the test. There is a minimum of one turn to create the item.",

    #Global Access
    "global access":"The Hunter is able to accomplish feats of digital larceny well beyond what a normal hacker is able to.\n\n- Edge Pool: Intelligence + Technology\n\n- System: To use this Edge, the Hunter must spend the equivalent of a scene (the length of time being determined by the Storyteller). The Hunter is then able to obtain data on any subject or person in any database, ranging from surveillance to buried records, upon winning a test at Difficulty 4. Without the associated Perks, this data may not be manipulated, and in the case of non-networked systems, the Hunter must have physical access to the local network.\n\n- Perks: Watching Big Brother, Money Trap, All Access Pass, The Letter of the Law",
    "watching big brother":"The Hunter can manipulate digital surveillance footage, editing people in and out of the records.",
    "money trap":"The Hunter can manipulate financial data and move money with little effort. This can be used to deprive prey or enemies of financial assets or guide authoritarian eyes toward something suspicious. This lowers the level of Resources of a target, when used offensively, by one per margin of the test. This reduction lasts for one month. The Storyteller should decide how this affects the Hunters when they use it for personal gain, with at least an increase in Danger as they line their own pockets.",
    "all access pass":"The Hunter can bypass electronic locks, tamper with, or disable security countermeasures such as alarm systems. The Difficulty depends on what the system is, with it usually being between 3-5 as determined by the Storyteller.",
    "the letter of the law":"The Hunter can manipulate criminal records. Making their enemies wanted criminals or erasing another's mistakes. The Difficulty ranges from 3 (local offenses) to 5 (global scale) when attempting to wipe or place them on someone else.",

    #Drone Jockey
    "drone jockey":"The Hunter has a drone that surpasses those that are commercially available. They are also able to control it expertly and repair it on their own. The type of drone varies, either as a tool for surveillance or for combat.\n\n- Edge Pool: Wits + Technology for flying the drone. Intelligence + Craft to either repair or rebuild it.\n\n- System: When obtained, the drone is equipped to perform two Skills. For example, a walking drone with armor might be able to perform Athletics and Brawl; a surveillance drone might perform Stealth and Awareness. The type of drone that a Hunter uses is determined when the Edge is obtained, and more variants may be obtained through the Perks. When a controller tests the Skill of the drone, either through the hand-held device or hardwired computer, they use their Wits + Technology instead of the usual pool. If the drone must make a Skill test for a Skill they do not possess, they use a one-die pool.\n\n- The drone has an unlimited range, and can stay active for one day plus additional days equal to the margin of a test made of Intelligence + Science at Difficulty 2. Drones have five health levels, with ground drones treating damage as Superficial and flying drones treating damage as Aggravated. By spending the equivalent of a scene and making a test of Intelligence + Craft at Difficulty 3, the Hunter may repair the damage of a drone by the number of health equal to the margin of the test. This can also be done on destroyed drones, but they must be fully restored before they can be used again.\n\n- Perks: Autonomous, Specialist Skill, Payload, Variants, Armaments",
    "autonomous":"The Hunter is able to run drones with simple patterns on their own. Complicated decision trees require a Resolve + Technology test as an appropriate difficulty. Instead of using the Hunter's Wits + Technology, any Skills used in this mode use a flat pool of five dice.	",
    "specialist skill":"This drone can obtain an additional Skill, and if the Storyteller agrees, this can also include the drone carrying items or manipulating the environment. Some examples are Larceny with a set of electronic picks or Science with an onboard mobile lab. This Perk only applies to one drone but can be taken multiple times for additional drones.",
    "payload":"The drone can carry cargo many times bigger than what it would seem to be able to carry. While carrying cargo, the drone moves slower and grants two-dice to those attempting to detect it. This drone will not subdue a resisting cargo, and the size of the drone should be agreed upon by the Storyteller and player before it's used.",
    "variants":"This Perk can be taken multiple times and allows an additional drone variant (complete with two Skills unrelated to previous drones). Only one drone can be active at a time, unless the Autonomous Perk is used to run them.",
    "armaments":"The drone is equipped with the equivalent of a submachine gun or taser, which uses a flat five-dice pool. The Specialist Skill Perk allows the controller to use their Wits + Technology when directly controlling the drone.",

    #Beast Whisperer
    "beast whisperer":"Some species of animals may be understood by and loyal to the Hunter. Thus, they are dependable companions and occasionally even friends.\n\n- Edge Pool: Charisma + Animal Ken for commands, Composure + Animal Ken for training.\n\n- System: When taking this Edge this Hunter must choose one type of animal and which key action pool it has. This animal is considered completely loyal and will accompany a Hunter into any situation as long as it is desired.\n\n- Perks: Incorruptible, Complex Commands, Menagerie, Incognito",
    "incorruptible": "The animal is immune to supernatural powers that would sway it away from its master.",
    "complex commands": "Animals can now understand more complex commands. Charisma + Animal Ken is used to give these commands with a Difficult dependent on their complexity, while Intelligence + Animal Ken is used to understand the animal.",
    "menagerie": "Choose another animal type and add it to the available pool of animals.",
    "incognito": "The animal can now stay out of sight, hiding either just out of observed range or blending into environments. The Storyteller should determine the plausibility of this in certain situations, depending on the animal.",

    #Sense the Unnatural
    "sense the unnatural":"While holding an object of focus, the Hunter is able to detect the nearby presence of supernatural creatures. However, this ability does not determine who or what the creature is.\n\n- Edge Pool: Wits + Occult or Science, depending on the Endowment's nature.\n\n- System: Upon winning an Edge test with a Difficulty of 3-5 (ranging on the type of creature and its power), the Hunter will be able to detect if there is a presence. The Hunter must hold their object of focus, with its use being intentional and obvious. In order to use this power more than once per scene, it requires spending one point of Willpower for each additional attempt.\n\n- Perks: Creature Specialization, Precision, Range, Handsfree",
    
    "creature specialization":"Sense the Unnatural: Gain a two-dice bonus against a specific type of creature when attempting to detect it. This can be learned multiple times, but only once for each creature type.\n\nRepel the Unnatural: Gain a two-dice bonus against a specific type of creature when attempting to repel it. This can be learned multiple times, but only once for each creature type.\n\nThwart the Unnatural: Gain a two-dice bonus against a specific type of creature when attempting to resist it. This can be learned multiple times, but only once for each creature type",
    
    "precision":"The Hunter is now able to determine who the supernatural creature in the room is, but they are unable to determine the type unless they have a specialization for it.",
    "range":"The range of the ability is extended to roughly the size of a city block, but it does not give precision beyond if it's in the same room or farther away.",
    
    "handsfree":"Sense the Unnatural: The Hunter no longer needs to use an object of focus for this Edge.\n\nRepel the Unnatural: The Hunter no longer needs to use an object of focus for this Edge.\n\nRepel the Unnatural: The Hunter no longer needs to use an object of focus for this Edge.\n\nThwart the Unnatural: The Hunter no longer needs to use an object of focus for this Edge.",

    #Repel the Unnatural
    "repel the unnatural":"By brandishing or otherwise using an object of focus, the Hunter is able to repel supernatural creatures.\n\n- Edge Pool: Resolve + Occult or Science depending on the Endowment's nature.\n\n- System: Upon winning an Edge test with a Difficulty set by the Storyteller (Default is half the creature's Composure + Resolve or just the standard Difficulty of the creature), the creature can be held back by the Hunter as long as they remain stationary with their object of focus. When repelled, creatures cannot move closer or engage them in brawl, but they are able to defend themselves and use any of their other powers. Should the Hunter move, they must make the Edge test for each turn spent moving with the same pool and Difficulty as before. If they lose, the repelling stops and cannot be used on the same creature again for the duration of the scene.\n\n- Perks: Ward, Creature Specialization, Damage, Handsfree.",
    
    "ward":"Repel the Unnatural: The area of protection can be extended to include roughly two meters around the Hunter, with an additional meter per margin of success.\n\nThwart the Unnatural: The area of protection can be extended to include roughly two meters around the Hunter, with an additional meter per margin of success. Anyone in the area receives the benefit of this Edge, with the Hunter who possesses it making all the resistance tests and spending the Willpower.",
    
    "damage":"The Hunter can use the object of their focus as a melee weapon with +0 damage and inflict Aggravated damage to the creature under the repel effect. If used in this manner, the Hunter must immediately retake the Edge test, or else its protective power fails.",
    
    #Thwart the Unnatural
    "thwart the unnatural":"Using an object of focus, the Hunter is highly resistant to any supernatural abilities that affect the mind.\n\n- Edge Pool: Composure + Occult or Science, depending on the nature of the Endowment.\n\n - System: While holding their object of focus, a Hunter is immune to supernatural abilities that would otherwise require a resistance test. For abilities used by the Hunter that would apply automatically, they may make an Edge test. This only applies to attempts that target the Hunter specifically and not to purely physical attacks or augmentations. For example, this would protect against mind control but would not protect against a creature attempting to rip them into pieces with their claws.\n\nPerks: Creature Specialization, Recognition, Ward, Handsfree.",
    "recognition":"If they successfully resist an ability, the Hunter is made aware of the attempt and what the power would have done. This, however, does not give them the exact rules but instead gives hints.",

    #Artifact
    "artifact":"The Hunter has obtained a rare tool, whatever it is, that provides more than a similar object would.\n\n- Edge Pool: Intelligence + Occult or Science, depending on the Artifact's nature.\n\n- System: The relic provides the Hunter with a one-dice bonus to a single Skill associated with it, however, this bonus does not apply to Edge tests for the Artifact. This can be used as an object of focus if it meets the requirements. Unlike other objects of focus, though, if it is lost, it requires a long ordeal to regain it.\n\nPerks: Empower, Detection, Attraction, Shield.",
    "empower":"Once per scene, the Hunter can make an Edge test at Difficulty 4 to increase the bonus dice to three. If this test fails, they suffer superficial Willpower damage equal to the amount they lost.",
    "detection":"The Artifact acts similar to Sense the Unnatural Edge and uses the same base system rules.",
    "attraction":"Many people seek out this item, and so it can be used as bait and provides a two-dice bonus to any ambush attempt. Be warned: once it's revealed, those who know will continue to look for it as long as they know its location.",
    "shield":"Acting as a supernatural shield for the Hunter, while it's on their person, any physical damage stemming from supernatural sources is halved. (Or halved again, in cases of superficial damage.)",
}
